services:
  todo:
    container_name: inventory-service
    build:
      context: .
    # prebuilt images at:
    # https://hub.docker.com/repository/docker/superorbital/inventory-service
    image: superorbital/inventory-service
    restart: unless-stopped
    networks:
      - my-net
    ports:
        - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/items?limit=1"]
      interval: 15s
      timeout: 3s
      retries: 3
networks:
  my-net:
    driver: bridge
